/**
 * Image Generation Service for Uma Chatbot
 * Supports text-to-image synthesis using high-definition AI models
 */

// Patterns to detect when a user is asking for image creation
const IMAGE_REQUEST_PATTERNS = [
    /^\s*(?:please\s+)?(?:generate|create|make|draw|render|paint|design|produce)\s+(?:an?\s+)?(?:image|picture|photo|wallpaper|drawing|illustration|artwork|graphic|pic)\s*(?:of|about|for|showing|with)?\s*(.*)/i,
    /^\s*(?:image|picture|photo|wallpaper|drawing|illustration)\s+(?:of|showing|for)\s*(.*)/i,
    /^\s*(?:draw|paint)\s+(?:me\s+)?(?:an?\s+)?(.*)/i,
    /^\s*(?:generate|create|render)\s+(?:an?\s+)?(?:artwork|illustration|wallpaper)\s*(?:of|for)?\s*(.*)/i,
];

/**
 * Checks if a user's prompt is requesting image generation
 * @param {string} text
 * @returns {boolean}
 */
function isImageGenerationRequest(text) {
    if (!text || typeof text !== 'string') return false;
    const trimmed = text.trim();
    return IMAGE_REQUEST_PATTERNS.some(pattern => pattern.test(trimmed));
}

/**
 * Extracts the core subject/prompt from the user's message
 * @param {string} text
 * @returns {string}
 */
function extractImagePrompt(text) {
    if (!text) return '';
    const trimmed = text.trim();

    for (const pattern of IMAGE_REQUEST_PATTERNS) {
        const match = trimmed.match(pattern);
        if (match && match[1] && match[1].trim().length > 0) {
            return match[1].trim().replace(/^["']|["']$/g, '');
        }
    }

    // Fallback: strip leading verbs
    return trimmed
        .replace(/^(?:please\s+)?(?:generate|create|make|draw)\s+(?:an?\s+)?(?:image|picture)\s*/i, '')
        .trim();
}

/**
 * Creates an image URL based on the visual prompt
 * @param {string} prompt
 * @param {object} options
 * @returns {string}
 */
function buildImageUrl(prompt, options = {}) {
    const cleanPrompt = (prompt || 'artistic landscape').trim();
    const encoded = encodeURIComponent(cleanPrompt);
    const width = options.width || 1024;
    const height = options.height || 1024;
    const seed = options.seed || Math.floor(Math.random() * 10000000);

    return `https://image.pollinations.ai/prompt/${encoded}?width=${width}&height=${height}&seed=${seed}&nologo=true&enhance=true`;
}

/**
 * Generates Uma's complete markdown response containing the generated image
 * @param {string} prompt
 * @returns {{ reply: string, imageUrl: string, prompt: string }}
 */
function generateImageReply(prompt) {
    const cleanPrompt = extractImagePrompt(prompt) || prompt.trim();
    const imageUrl = buildImageUrl(cleanPrompt);

    const reply = `Here is your generated image of **${cleanPrompt}**:\n\n![${cleanPrompt}](${imageUrl})\n\n*Generated by Uma AI · Prompt: "${cleanPrompt}"*`;

    return {
        reply,
        imageUrl,
        prompt: cleanPrompt,
    };
}

/**
 * Streams the image generation response to the client
 * @param {string} prompt
 * @param {function} onChunk
 */
async function streamImageReply(prompt, onChunk) {
    const cleanPrompt = extractImagePrompt(prompt) || prompt.trim();
    const imageUrl = buildImageUrl(cleanPrompt);

    const parts = [
        `Here is your generated image of **${cleanPrompt}**:\n\n`,
        `![${cleanPrompt}](${imageUrl})\n\n`,
        `*Generated by Uma AI · Prompt: "${cleanPrompt}"*`,
    ];

    for (const part of parts) {
        onChunk(part);
        // Small delay for smooth streaming UX
        await new Promise(resolve => setTimeout(resolve, 80));
    }

    return { isImage: true, imageUrl, prompt: cleanPrompt };
}

module.exports = {
    isImageGenerationRequest,
    extractImagePrompt,
    buildImageUrl,
    generateImageReply,
    streamImageReply,
};
